apiVersion: v1
kind: Secret
metadata:
    name: ghost-mariadb-secret
    namespace: ghost
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:H+2VZ8+aezQ1kqY1BfkthOG40sbhpcEOTLhcSkhk2PKdmZUT++dJ/o4srHo=,iv:/LTkQSJ6TXNGEBOhwmq9Y53pTsdU9+IqwyZ3uGC4GFg=,tag:BuzHKpdhfWB+OYAnyk94/A==,type:str]
    db-password: ENC[AES256_GCM,data:PJmomHS/nhx3BOLgYnLi7dIMPIm+sBRiEjyo8DtQkjbLs/2e+QIKaj9Usos=,iv:fBrmn3k7+7HTdKvVgc1N5Pwo/a4ZsDTVGnxsfQVCrgU=,tag:7vXC1bpAUVtqGEEMbF4+1w==,type:str]
sops:
    age:
        - recipient: age15dt7js8n0zr4znk3a5lu7d74krv4qqlh48xymvjy76cmplhn5qpqw9q0pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WnFuYnNnbkFyamdTQXh0
            ZXN5eEUxcVVISDdkRUt6L2V5K09hTUFiaVRzCjNaUjJHSEJMelZrK1VlREoycWg4
            ZFVZNnNlWG5vQllFcmpPZE5RaUlqNVkKLS0tIHhDa3MzUkNKZUdnRW9GcmdDU2NB
            NmN0dU9adEl6bEdDOE1Day8ycUVPR2MKSoUldJYh87S3wLgv2tauGlmCyvNWiGAI
            M+l6+K1ex0Ob5r955e06OdNVVo7YtawOefCw4xBsm2YzP54heIWu3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:50:17Z"
    mac: ENC[AES256_GCM,data:gahFIFFtTrZ5cThx9AMWsjHLJixtsgZa0ZeJkeJSmZo/GRceAadeJMxhoXtG+7DQQ2ufQJjWDGjlcMhYWVXYcbvBT6f5EWZ3Q63U+VF+nxMhPuV9hJOvUx0pPI6Njgx4obU0GpGcQi75H8SwxoSgmBuachdcqiqetfE7MbxLSVQ=,iv:c4aAiYvtWjWnMd6sKr9nNRktzVCDqDZuCltolt72TXQ=,tag:x29GMzZvR8hOI9GObmqtzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0