apiVersion: v1
data:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:5Mr0qo81JMqJLqI4XN82GSOPloB7q/kFbDsiNppxFZLGPZd4px/3Zj1RU3onGJVnAeRE6tYoWVncFP60KUhJ9A==,iv:1GXoKkP8Jgkifil+XVAnJ1cmEM9c89NJ6RQiZRWigTc=,tag:GXhVEEOBXjHYkyn5Bwsq6g==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:g2jSFy0TX9qBZlEcVexI2vX+IYdds/SVeRUWwYgKbO+2rM5VxrtUt8lNxc1FRFNWBiIHz59NthpFCRfu6TZJ8Cdg9GY=,iv:FtbT8A9/4JH6Kx5ffPlOVUJWUaSLfyYLiWS4XyS+KTo=,tag:qigJMb4qweiOcNtzqUXAxQ==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:Qp3alyaqP/Lps+Ntt+kMtxrdfSG6H7vQUjrzzyxhCiAlYeI53Z/IPK7nHZiWTZsSjJRJdnvpLD5/vFTI9i+2rA==,iv:x8RXUbYpLaaGvU4meGggRuVEQEbYuZexSXO6vn/aBjA=,tag:wZ0WPm21ANxaqBprWlpS+g==,type:str]
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: karakeep
type: Opaque
sops:
    age:
        - recipient: age15dt7js8n0zr4znk3a5lu7d74krv4qqlh48xymvjy76cmplhn5qpqw9q0pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Zm9hb1dGRzhTakpYY3JV
            ZjlTMmRNMGxsbThXRUZRbVE4UVZjcEJ4MDBnCjNiNXE3NjBtSkJTbC8vMVgwOGhO
            dTl6OFZMcmhUNEQxS2NPSVhBL2k5ZEEKLS0tIE4rY1JSbjFubHhoWHNSM09xYURD
            dnlPZ3NtMjNYNHFrUS9VSVk0bVRreWMK87zlSx+9vDEYpSmqT7tVUToqBo5JgCTR
            OmCYxjsMW8x8R9XuR9ZRUKU3ELFYXvtDpA0Wi52kzh6/hoch44fEiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T14:02:44Z"
    mac: ENC[AES256_GCM,data:NPMNVJZGEoLRX0o1vHYxp6qT5K+PiL9HWFfqztaem7pAr/Qx8cpeX5BzGM7oX+tAKEsojCuBffV/z7w5j6NEc58fmIOgO1VfUXUN2ogCMMHj6rUCOpd/lAlAQKG3G2shrSPgeLEMa5s7mtNbMbkWaOTNk1CjTjTCjxIxy1eJ3co=,iv:TIMGCIHNLQC60htKyb5OnuHhxSoW+WberBAGFDbDF54=,tag:WKr1t4s4JOT+MLPTLpweqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0