apiVersion: v1
kind: Secret
metadata:
    name: odoo-master
    namespace: odoo
stringData:
    admin_passwd: ENC[AES256_GCM,data:dLlJpuKSWcu6U47yZvLEz5Ca5kcjlBi2UuKPaGuy438NtKIhICnTk81UUeo=,iv:Dar5xxYbltL86wMroolZUvBIaXyZ9yBH4kSukKmj6NU=,tag:01VlJpZCpfDn0Ryj5ACwFQ==,type:str]
sops:
    age:
        - recipient: age15dt7js8n0zr4znk3a5lu7d74krv4qqlh48xymvjy76cmplhn5qpqw9q0pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc1pZWGpaVmZSVlViNXNF
            cTFtQURJeWx4eC9oZ2FZTmJxNzFhOGpUVmh3Cmp6MVFET1dzcVozQ09hSGdMamsy
            dVo2aEphSGVSeXdZd1VaQ2xJRk12cjAKLS0tIENVQ3NSN3RocUVteW9TQnJzNGN5
            U2ErN3VNSFd6ZXdSZGVSUnRKTXgrTUUKlex5O1cgmYoezTwlq2TSOOSe0Oz0zucs
            0CYZz3pOJUNmOpRihrd34uNp/2ZQPqpOOafmgnzlMY1wbZCAxe4x3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T04:42:07Z"
    mac: ENC[AES256_GCM,data:N2r8Jh8fW+FxXjz1dHTpH2lF3pHyszeKnJ4u8JBT4gV6Qt0xuZILGoaABc7R2eVTNNpArHw0BrNMrHMiEN354niIYNvsM4IbXqXInOJHqWrAUzIGbzwE2tkYzyLMUDwyA5A8WVo2l44CxYwM+MSMfCicCAdc16KyqgT7XqN4okA=,iv:j+cJCYmSMsZT8Q2fEJKhIbutBA4/Ybq9tQf/L9RmjDQ=,tag:I5ZS7gpqPIrASSlS4Nl/mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0