apiVersion: v1
kind: Secret
metadata:
    name: romm-secrets
    namespace: romm
type: Opaque
data:
    DB_PASSWD: ENC[AES256_GCM,data:W0I7b9grwCTfOpf0T+90rfd3JUaomEj749cWr4L5obzdFHCcwet/nPMMz2Sk32RKCDiG/S1njXRN9/8cLB2klQ==,iv:iTRZj3ZCn/R8cW1SH4pVX6eGKjdgqqapzO/VgTar37I=,tag:HNkOrVlHGvr/PDb1k984CQ==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:8tetIRYAtgjK+74X3x5MLWcC6V1EpOmHkmfJjigooSv32azYe7DYhMrOxPN5jQ8OxyoIqR4RANE9impND+ikTQ==,iv:6JFOxa1ROow7J4ZmSj2+TV50f9/g+WFdaeONndLhRSE=,tag:ioySvyZFS8ueSTsVGSkTXg==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:SFt4hYXD+91LqQTdgh9nPjUiCmCPZxz/4B3lIVoa8wZOwPurdCJsGZ1p3qaQY91ipuyumKXk+dVWl++D4S2/gA==,iv:+gZ2YPrrBlJAG9JsG5ztir3uNCvFzTQVjRDGvKLi0AQ=,tag:aVHYSS0vZR0WrJH8gHW1tw==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:hq8h57qMqMBaPvyWZ5o7fEtEIODdgOpaj4qpHFFLego/x240Gh4BPsii5meLQS98i1nP8SCnjY4T2LYgtC6gXw==,iv:kJVPC5fCidqrWWZJHnrv6oAOcorS71+05AcC/MOv6ro=,tag:u7UBhVtDP+UPkUu8KgkDOg==,type:str]
    #ENC[AES256_GCM,data:Qyl9R8HV5d69/kZEmZKCwhiY7/ymHVdsgWkClsHkDcjriT3J5+nCQEVCGuM=,iv:DS6ynae4OapOZgUaVAeE61W3STUawJTX5vtdaaMjWPE=,tag:AkYBqrSVtsBx7XvYyYChaA==,type:comment]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:oRL8IkcUGgUUHDiNNOBVtRSDwcNCQthpZryAqYmg6sY/bC77ywmu8/tYx6A=,iv:GEQ+4daUbhgeELBhcMqlv47pE8Avky/ZAv3UsI9V1hU=,tag:GFkl2n4lxbBgi5+Q+kS4fA==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:cLeqi0evOTqJd8MkuB+/yBDgtEc5CoVjO2HS25ktJbqqTeL7uIWnv+fDN7g=,iv:GhkfG4wM7FUPlgs2+u7Q7CH66saxMlrCMz9PKq87t+U=,tag:rhdFEOBrgqd6iCvWzry7Xg==,type:str]
    MOBYGAMES_API_KEY: ""
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:dYbJlmaO0JPyE4+SOCI1Akme9TvXjPcvQjpRWIN1qZmOa/UgI2D/Nl2OTaM=,iv:gKe3yrxIS/eqCdb2KCONjAL6Zv0ggpVCyFuvSKz69Ao=,tag:AfHqDVhvjEg2ABpzBHetpg==,type:str]
sops:
    age:
        - recipient: age15dt7js8n0zr4znk3a5lu7d74krv4qqlh48xymvjy76cmplhn5qpqw9q0pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM2cwOW4rdjRESFE0TVlG
            K29iSGc5eDNFU29BcUw1bFZZRzRSRGJkZ0UwCmt1OGtqNnlZc3F0Zy9GMjE2R2U2
            d3g5U1pOQ2pob2h6MmhhVW1EczVJd3MKLS0tIG5tT1lUMk5SOTBtLytvRi8zaitV
            OWZUaXpGYVUxY0JGMFlqQ0gvRTBpOG8K8XL+qTDnss33ZRrMmIr3imQAYHu1zvtN
            d+JC+BE62jna+y+P0gFY2h/9DeEtRmYal0p2H+9aU/V9MMWFdbXeqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T13:59:08Z"
    mac: ENC[AES256_GCM,data:DSfP4ocYFmIN2m9ck2W3XRAEncT6E+ppJxG/Sy66m+cXiUSP9fzeRKdxyzoPp95tScjaJXck+w/WC3MBcGzJQlWbYBHbl0qyQ0AptAdRZtFG8NX6NKmACL0queSI7k2egMBOy1I+t2UzgMea+v8fCCb08/SuhFM1aogOVBZMrEk=,iv:/Axm9qUtuiSGJa8mOL3cnJg5/dHZFiFLKUepO40szgQ=,tag:OnLHDsQmmKIPbIcuudzInA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0