apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr-release
  namespace: homarr
spec:
  chart:
    spec:
      chart: homarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: homarr-repo
      version: 5.8.0
  interval: 1m0s
#  values: