apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      sourceRef:
        kind: HelmRepository
        name: homarr-oci
        namespace: flux-system
      # pin to a version you’ve tested; current as of 2025-08-30 is 5.9.0
      version: "5.9.0"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable RBAC so Homarr’s Kubernetes read-only dashboard works
    rbac:
      enabled: true
  
    # Disable persistent storage for now (no PVC)
    persistence:
      homarrDatabase:
        enabled: true
        size: 1Gi
        storageClass: ""

    # Ensure /appdata exists using an ephemeral emptyDir for testing
    extraVolumes:
      - name: appdata
        emptyDir: {}
    extraVolumeMounts:
      - name: appdata
        mountPath: /appdata