apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ../../infrastructure/cert-manager-crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml