apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  resources:
    - cloudflare-dns-challenge.yaml
    - bourne-cloud.yaml
    - tlsstore.yaml
  dependsOn:
    - name: cert-manager # Wait until cert-manager CRD's are installed.