apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values: {}