apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.13.6"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    service:
      enabled: true
      type: ClusterIP
      port: 5678
      name: http
      annotations: {}
# Disable PostgreSQL since we're using SQLite
    postgresql:
      enabled: false
    
    # Basic n8n configuration for SQLite
    config:
      database:
        type: sqlite
        sqlite:
          database: /home/node/.n8n/database.sqlite
      
      generic:
        timezone: UTC
    
    # Disable persistence for testing
    persistence:
      enabled: false