apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: ntfy
data:
  server.yml: |
    cache-file: "/var/cache/ntfy/cache.db"
    attachment-cache-dir: "/var/cache/ntfy/attachments"