apiVersion: longhorn.io/v1beta1
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  type: nfs
  nfs:
    server: 192.168.1.10
    path: /mnt/storage-zfs/k8s-longhorn-backup