apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    manager:
      hostPathMounts:
        - name: dev
          mountPath: /dev
          hostPath: /dev
          readOnly: false