apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: bookmarks
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "3.x"  # any current 3.x release
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: sissbruecker/linkding
              tag: latest
    service:
      main:
        controller: main
        ports:
          http:
            port: 9090
    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: links.bourne.cloud
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        enabled: true
        size: 2Gi
        accessMode: ReadWriteOnce