apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: karakeep
spec:
  ports:
  - port: 9222
    protocol: TCP
    targetPort: 9222
  selector:
    app: chrome
  type: ClusterIP