apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - meilisearch-pvc.yaml
  - data-pvc.yaml
  - karakeep-web-deployment.yaml
  - karakeep-web-service.yaml
  - chrome-deployment.yaml
  - chrome-service.yaml
  - meilisearch-deployment.yaml
  - meilisearch-service.yaml
  - configmap.yaml