apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: lan-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - lan-pool
  peers:
    - lan-router
  aggregationLength: 24
