apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.105.20.210-10.105.20.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dmz-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - dmz-pool