apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
  - lan.yaml # Ensure LAN Pool is the top of the list so it remains the default choice for newly created services.
  - dmz.yaml