apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - romm-mariadb-deployment.yaml
  - romm-mariadb-service.yaml
  - romm-deployment.yaml
  - romm-service.yaml