apiVersion: v1
kind: Service
metadata:
  name: romm-service
  namespace: romm
spec:
  selector:
    app: romm
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP