apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  # Add sites available below:
  - ingress-nginx-test.yaml
  - ingress-longhorn.yaml