apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-filestore
  namespace: odoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi