apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "3.5.1" # pick latest
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.13 # pick latest from Docker Hub
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      data:
        enabled: true
        size: 5Gi
        accessMode: ReadWriteOnce
