apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "3.x"            # any current 3.x works
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: "latest"
            env:
              TZ: Australia/Sydney
    service:
      main:
        controller: main
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: status.bourne.cloud
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
    persistence:
      data:
        enabled: true
        size: 5Gi
        accessMode: ReadWriteOnce
