apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-web
  namespace: uptime-kuma
spec:
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app: uptime-kuma
  type: ClusterIP