apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |
    [options]
    db_host = odoo-db-rw
    db_port = 5432
    db_user = odoo
    db_name = odoo
    proxy_mode = True
    list_db = False