apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configmaps
  namespace: flux-system
spec:
  interval: 5m
  path: ../../configmaps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: storage
    - name: secrets
    - name: repos