apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-disks
  namespace: flux-system
spec:
  interval: 5m
  path: ../../infrastructure/longhorn/disks
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn: 
    - name: longhorn