apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-db
  namespace: odoo
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: postgres
      owner: odoo
  storage:
    size: 10Gi
    storageClass: longhorn