apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: odoo-db
  namespace: odoo
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  bootstrap:
    initdb:
      database: odoo
      owner: odoo
  managed:
    roles:
      - name: odoo
        ensure: present
        login: true
        createdb: true
  storage:
    size: 10Gi
    storageClass: longhorn