apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "3600"]
      stdin: true
      tty: true
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-lb
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: lan-pool
spec:
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer