apiVersion: traefik.io/v1alpha1
kind: Service
metadata:
  name: nas-service
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - url: "https://192.168.1.10"
      - url: "https://ui.nas.bourne.cloud"
    serversTransport: insecureTransport
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nas-ingress
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ui.nas.bourne.cloud`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
      services:
        - name: nas-service
          port: 443
  tls:
    secretName: https-nas