# clusters/my-cluster/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-test-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./nginx-test # Path to your NGINX manifests within the Git repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system # Or the name of your GitRepository source
  targetNamespace: nginx-test # Or the namespace where NGINX should be deployed