apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi # adjust storage if needed
  resources:
    requests:
      storage: 10Gi