apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi # Adjust based on your ROM collection size
  volumeName: romm-library-nfs-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # For saves, states, etc.
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # For config files
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi # For covers, screenshots from IGDB
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-redis-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # For Redis cache data
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-pvc
  namespace: romm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # Database storage
  storageClassName: nfs-csi