apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  # Public repo over HTTPS (read-only)
  url: https://github.com/Kylindrias/K8s-Bourne-Cloud
  ref:
    branch: main
  ignore: |
    # optional: keep your repo lean for the source downloader
    .git/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # You can leave this in now; it only kicks in when you introduce SOPS files.
  decryption:
    provider: sops
    secretRef:
      name: sops-age
