apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: dashboard
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/heimdall
              tag: latest
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: bourne.cloud
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        enabled: true
        size: 1Gi
