apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: nginx-test # Or your desired namespace
  annotations:
    metallb.universe.tf/address-pool: lan-pool
spec:
  selector:
    app: nginx-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Or LoadBalancer if you need external access