apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: nginx-test # Or your desired namespace
spec:
  selector:
    app: nginx-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30800
  type: NodePort # Or LoadBalancer if you need external access