apiVersion: v1
data:
    db-encryption-key: ENC[AES256_GCM,data:rrVYX72XS+gXj0djGHB2Gza/S4WBr5wEqPMdL9Exyrybl6FEmxvgFle5sbklf8rl9l25k2PGGuchC2YqGYZXtIJPv0YGwQfGJDfaXwvUWVK2JBkiv0s4DA==,iv:sNP2lFseP6PXyGCz/0CIAf3u0cuPuA9NTaFTnluaXsw=,tag:hXdH4Qp2582L1JSPHizThg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-secret
    namespace: homarr
sops:
    age:
        - recipient: age14tpyf3lz9gj90zkq7dnchggahqzsfrqama2sd7kycmdw97sg05dse8c79t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUkhWNXY0VFpVeFFpNjZB
            dWNtV1hORUhUeVB1UXZPZTFJdFlBVWtnalc4ClRUUmVSY3hBQlZlSmNpVkFmSWtX
            NExFWEd2MTRUYzNKZDBWUGl0d3Z3Z00KLS0tIG83R1hmZFVpSTFPZHpxUjlTU0ow
            ZXlaRFdlNmVBa0xmditoSkxiVXZRNm8KCTADIRKKvDb3lp6klurUTVDR7osdIG+r
            dZVFG8C0ao6MhUIL9S7YWNQU/juI34OdsIIsqK/PUPXXTDbXZ3c/+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T04:46:19Z"
    mac: ENC[AES256_GCM,data:gyLDh5uJIfmaJICCFSOhI8RdtoYL8PQswTYN/zYBX+oP/r01D+DMWZLbW3/899RGsW0vZ6uTkMx9gQzkLJY9aob1nUJIYsgJcpaiMZ4gVa/wiYJX/lzyF1wwjCZeITLalRDxjHoaCBXzQsFGLLZkrxbwozqJhOrvdjWrSWxsmEg=,iv:IPNq6bPxr9I5ckroemTKtvA2ELpjIimlXFCqnwmDWIY=,tag:XOtx14GYjYfBLRsDM6IotQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2