apiVersion: ENC[AES256_GCM,data:q+g=,iv:Zp2SsfbUtcrSDGHL34H/S6jLoso7/wPz3FYS/1IJEGk=,tag:0PzCDn/6vVnniMGwDlJ2YA==,type:str]
kind: ENC[AES256_GCM,data:VEJ2xBj7,iv:R9lzEujF+YLw+C9GMCdCNMyJM5SY2tsXN0IbnYaP4XE=,tag:qdVQozijTG2cd1WdoNLm/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:esDBQwZATYkI,iv:5KKHLu2F7zvWwQjLhsx0fBjpPYa2ngRk0ucWKdUyFJA=,tag:mcWBLIpjkL/z4yRgXpJZ/Q==,type:str]
    namespace: ENC[AES256_GCM,data:PlMgEsr8OA==,iv:X+gdi80S1VUe++327sOPRzw5PYr+J3Gyekkyge7vX/g=,tag:pZAqteNaTFWpEnGzmzKRMQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:eY+PgZPq/t4mH9iPYnc=,iv:5LwIjIl2cSLS+KuzK4OiU9UyC8xNZj/PwF+8hq/6m3Y=,tag:igeuBs1xlQGfRYQbQpDCiA==,type:str]
sops:
    age:
        - recipient: age14tpyf3lz9gj90zkq7dnchggahqzsfrqama2sd7kycmdw97sg05dse8c79t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQng1Ym55L1lDVXdlMEhj
            bFZrNmtHOGJ2endCNWg0bnJmbVJSZFIrKzJBClBnV045NHlRNGxkWDVBSFBRRjdk
            UGl4RHpUWUhBSFE1TzNMQ014RU5vY2sKLS0tIDdzT2NneWFjWkY3N1IyQkhsc1B6
            dk1NcnZod2tuWTE0cVlZQ1lyYzJWSjgKhsLZaB24p1zdTMKghYezyoQ1SD+Oo1Mk
            lCCXjmuV2f5bg5p2mOQUhqQxsJqud5OGLCS77EEbMwPJolgbgbDOsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T05:51:59Z"
    mac: ENC[AES256_GCM,data:45w1KaDKu1nJcDHa2+8XcwmRnEt0JWbvPl6CJZd3t7fT9UGw6xzi6X8W96XeOIJ1K081k/zmJuzQjd83LORqMbomWU1XZGNlel2JnTZgWA4G/l3JQAuMBZnNIH5qLGsGac3nEenkM1WrUBT0HkxGGr4JkNu5rXE9x0oWkfDKuZo=,iv:FoOC7QOLC3XxQ2mQPCOl2CAsLpB4RlhUqjqqaIh73cs=,tag:PIuHTnw0VbU+7kKDiOk9ew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
