apiVersion: v1
kind: Secret
metadata:
    name: romm-secrets
    namespace: romm
type: Opaque
data:
    DB_PASSWD: ENC[AES256_GCM,data:hDx/JKa1EsCvBHUrY7MMj7dU43goqxdK90TUWveCyEh8fDAuARCKNz4aR3m3w7cva0lGxcPTGoN9HMQAHOxiyg==,iv:SKVTrc+ZZCfADsqOtnFOAmJyhsAZWfl5+alUxlzisEw=,tag:b5o4weEgcNOkX4aEFNGajw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:NI8FiV53N3jrI7vvlWRpqEde608HVcXNfx/fi298Ogi8e4K+DahwGrqRT4qJJgNWwzkvjiFK4q8FY1luBoFnqg==,iv:LqYGvgR1G5XQ5F1RhObdibqsM1P/Irhk/4GVSs6DWsY=,tag:Pw8+GU9g/aeva3nXSoTISA==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:3DMdkmubseINfwJ1XRFmN9AZs4jhNg0zeY/Pbjieyo55jtph4w986MBATEGlFwpKWxmIV/dsUnBNPURuuOB31g==,iv:2oXw+N/qAcbH0OxjuR9XwWT/IWBh8PqGlt8xTh8ap7I=,tag:VVR2cPVFNOwGuzru4sqvmQ==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:hiu8Dz2XPYLWLutxCJVx6P+nBw3QYr+o1bJVrgVa7A+hbJp2VYWrdWFgNJDiqR4qCrw4+1C/y+FFSVj/mPsIGA==,iv:ALGD5JW9zVSgL9UKYZmd64XKI4wWRVCzWkqanOX4iI4=,tag:/6/eLqkY8mLLfIidM6DfRA==,type:str]
    #ENC[AES256_GCM,data:fvsuxfRx75zlqErL5ttcyP+Am3gP+O+buCqqmR5JERj3ru6MguFZU8/Fv0g=,iv:gE+oXfKo4uLW+uNRKu+EQBniS9fOMVAoTmvenhKilIw=,tag:bxDjZMjBF9t6UYyyF8JqIA==,type:comment]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:pLc++bMsq19TGHhN+KYqP3mE1JvYR4az/RAAgsK6,iv:/sv7GOKJgfM9pCZb8Vh3Q/JCiea7UxARKkMeJBKc5aM=,tag:dL/EEaTZnaNeJ76MMjWVfw==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:HzOF428Ch9hmkwFxm0x6vGjZidl8oGkqbQ8hE7/m,iv:BEdBE5X9EYIDQLpovooDto2Z0kqx3tElrT17wANdFj0=,tag:K6gh5un9l0LQKy6DNHFvoA==,type:str]
    MOBYGAMES_API_KEY: ""
    STEAMGRIDDB_API_KEY: ""
sops:
    age:
        - recipient: age14tpyf3lz9gj90zkq7dnchggahqzsfrqama2sd7kycmdw97sg05dse8c79t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dmpNT0JTaVlJclZ1TW1X
            b0Qvbm4vMVlia1hVN2xtdmV2dTg0Z3EzNlhFCklJTEc3MkVIWVd2dWlXTk80R2Vu
            b0lJV3FHa1hTMmtqSW9nNm5sekZ0T0EKLS0tIExzcTdOV1NJWm9ocG1UZ1lJa2ZG
            a2hlZHBUN1RBNEZWc0NpcFFUY1hseTAKqH6HTnmdSdjU7QoAdU0SGozORCFoHMdp
            LQQQLwSwA66C1Hyz8SgHqxol2i0pjRukXyYJPwKChmjYGLwTpiu+zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T15:29:52Z"
    mac: ENC[AES256_GCM,data:rfWU/HXL/HJj3sKBlrp9D7OHgnpN9J2e5CFUb8JtniEeSuUyaiPbXpXDToVrSL6ZqBN15wboOWPEMgjBQrlCyevqQJ1ndFaxYyu2yzmyLq5TlvOXjMjr/Jm0zPjO4xREdqdstlpJDjJ5uKhqGTANw0d95jjcu2mhhfCUnl/SulU=,iv:ontBpNY757dDgWKGbbJDQuZOGRDgMfkRpHhshoFSNhU=,tag:AqhhJL1GHVGpFJ9RZ7kIHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2