apiVersion: ENC[AES256_GCM,data:hhM=,iv:pfGf0TvFJdYOHAJDYfbKFuNVLx6Nk62uthr9JCk4Rv8=,tag:X3dVHpPxtPBKT9mAJfGpUw==,type:str]
kind: ENC[AES256_GCM,data:BcOnxcfY,iv:WtVL9s8uhYxr4QomFppIQvujEKK+rEoZ7H1goYy+7R0=,tag:v6r9xnUIHcspjXZscreeng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W27yo5a1Jc/c3ZCL8I2EKBMMCjiJ/g==,iv:jXgD0F+E0q9iS5/rJUEZbfjdl4ILdHGQLPQr6Sz8C5U=,tag:7E+z/mk1xlSls00MM/3cCA==,type:str]
    namespace: ENC[AES256_GCM,data:5GLEzlssdw==,iv:O+dZOJfORu3olfW92wJMFq/LxxbIpMIKdrHVfNex+mk=,tag:kpviXUt/zvL8adAAa47Xpg==,type:str]
type: ENC[AES256_GCM,data:uhKvj4cO,iv:SZFqpllbtlxr6P82v0fEZZJrYdD8I5D8s4wBufn+O+Q=,tag:mGCXRFm6JBFztBO/b9tdoQ==,type:str]
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:b8lFLkwUSLaY9P4GNtWv4w4XKqLcKloPk7wJYjF+WtMn6m8UjZUrxQ==,iv:z5gnX5FEyTwK9f3S0nRtp2/LItuUbokpZr6kTaMnXiE=,tag:65ugdKeDuoG1SJEuTQ3BKg==,type:str]
sops:
    age:
        - recipient: age14tpyf3lz9gj90zkq7dnchggahqzsfrqama2sd7kycmdw97sg05dse8c79t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TGg3MDBQTHZIVnNUTlV0
            eHFOMVRpejJFaUpjeXRIMVdpVHhrajV6L0g0Cldobi9sRnI5TTlSQ2hHSWtQaWpa
            NEdibkNWTXV4VkZQNWp0QzU5NDcxV3cKLS0tIGRkU0dOUGxjSHZvVTZYRDFCMnFy
            Qml2OTVhakYrajJxS09JSVo5L25nLzgKZVjH+IAZAclA5lCxtBrE5Hqc8JAxQsju
            qvPzHGjep0JV3ecCuCfipwnC0Zs8o1MI/l6O32oGn0a5w1rSUh+VOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T16:06:05Z"
    mac: ENC[AES256_GCM,data:zBfK6QMSXJu+RUihBx+fCymh7dsEfk/a7LA884o/tlYXRavSymdLBoEHgNp2RhPIZ7NXbpxgoSl9XGYaA5Ig+kOlplDjD8z3gmTKPWHS2YaitHh6wRKxVdxIW9PjkBc2XB0hzl8plqwYZf80Q3Ai39KP7OkmEd08eR1jQuvi07c=,iv:FZb3J+xXzatYhcDLmU8D55o5BFVCBXqVWgyEIPJ4aF8=,tag:6TMaAWeUeWNg9Q3jwpi8Ng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2